-- -*- mode: sql; sql-product: postgres -*-

-- id integer generated by default as identity primary key
-- id serial primary key

-- -------------------------------------------------------------------
--  objetivo
-- -------------------------------------------------------------------

create table objetivo (
    id integer generated by default as identity primary key,
    descripcion text,
    fecha timestamp with time zone default now()
);

create table comentario_objetivo (
    id integer generated by default as identity primary key,
    objetivo integer references objetivo (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  anotacion rapida
-- -------------------------------------------------------------------

create table anotacion_rapida (
    id integer generated by default as identity primary key,
    fecha timestamp with time zone default now(),
    contenido text
);

-- -------------------------------------------------------------------
--  cuenta
-- -------------------------------------------------------------------

create table cuenta (
    id integer generated by default as identity primary key,
    nombre text,
    clave text,
    descripcion text,
    activo boolean default true,
    fecha timestamp with time zone default now()
);

create table comentario_cuenta (
    id integer generated by default as identity primary key,
    cuenta integer references cuenta (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  enlace
-- -------------------------------------------------------------------

create table enlace (
    id integer generated by default as identity primary key,
    nombre text,
    direccion text,
    fecha timestamp with time zone default now()
);

create table lista_enlace (
    id integer generated by default as identity primary key,
    nombre text,
    fecha timestamp with time zone default now()
);

create table etiqueta_enlace (
    id integer generated by default as identity primary key,
    nombre text
);

create table enlace_etiqueta (
    enlace integer references enlace (id) on delete cascade on update cascade,
    etiqueta integer references etiqueta_enlace (id) on delete cascade on update cascade,
    primary key (enlace, etiqueta)
);

create table comentario_enlace (
    id integer generated by default as identity primary key,
    enlace integer references enlace (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table comentario_lista_enlace (
    id integer generated by default as identity primary key,
    lista integer references lista_enlace (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table lista_enlace_enlace (
    lista integer references lista_enlace (id) on delete cascade on update cascade,
    enlace integer references enlace (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now(),
    primary key (lista, enlace)
);

-- -------------------------------------------------------------------
--  gasolina
-- -------------------------------------------------------------------

create table gasolina (
    id integer generated by default as identity primary key,
    litros numeric (10,2),
    precio numeric (10,2),
    lleno boolean default false,
    fecha timestamp with time zone default now()
);

create table comentario_gasolina (
    id integer generated by default as identity primary key,
    recarga integer references gasolina (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  nota
-- -------------------------------------------------------------------

create table etiqueta_nota (
    id integer generated by default as identity primary key,
    nombre text
);

create table tipo_nota (
    id integer generated by default as identity primary key,
    nombre text
);

create table nota (
    id integer generated by default as identity primary key,
    nombre text,
    descripcion text,
    contenido text,
    tipo integer references tipo_nota (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

create table nota_etiqueta (
    nota integer references nota (id) on delete cascade on update cascade,
    etiqueta integer references etiqueta_nota (id) on delete cascade on update cascade,
    primary key (nota, etiqueta)
);

-- -------------------------------------------------------------------
--  pago
-- -------------------------------------------------------------------

create table pago (
        id integer generated by default as identity primary key,
        descripcion text,
        cantidad numeric(10, 2),
        fecha timestamp with time zone default now()
);

create table comentario_pago (
       id integer generated by default as identity primary key,
       pago integer references pago(id) on delete cascade on update cascade,
       contenido text,
       fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  fiado
-- -------------------------------------------------------------------

create table fiado (
        id integer generated by default as identity primary key,
        descripcion text,
        cantidad numeric(10, 2),
        fecha timestamp with time zone default now()
);

create table comentario_fiado (
       id integer generated by default as identity primary key,
       fiado integer references fiado(id) on delete cascade on update cascade,
       contenido text,
       fecha timestamp with time zone default now()
);
