-- -*- mode: sql; sql-product: postgres -*-

-- id integer generated by default as identity primary key
-- id serial primary key

create type mes as enum (
    'enero',
    'febrero',
    'marzo',
    'abril',
    'mayo',
    'junio',
    'julio',
    'agosto',
    'septiembre',
    'octubre',
    'noviembre',
    'diciembre'
);

create type prioridad_tarea as enum (
    'baja',
    'normal',
    'alta'
);

-- -------------------------------------------------------------------
--  aniversario
-- -------------------------------------------------------------------

create table tipo_aniversario (
    id integer generated by default as identity primary key,
    nombre text,
    fecha timestamp with time zone default now()
);

create table aniversario (
    id integer generated by default as identity primary key,
    tipo integer references tipo_aniversario (id) on delete cascade on update cascade,
    descripcion text,
    dia integer default extract(day from now()),
    mes mes default 'enero'::mes,
    fecha timestamp with time zone default now()
);

create table comentario_aniversario (
    id integer generated by default as identity primary key,
    aniversario integer references aniversario (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  cita
-- -------------------------------------------------------------------

create table cita (
    id integer generated by default as identity primary key,
    texto text,
    autor text
);

create table comentario_cita (
    id integer generated by default as identity primary key,
    cita integer references cita (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  diario
-- -------------------------------------------------------------------

create table diario (
    id integer generated by default as identity primary key,
    evento text,
    fecha timestamp with time zone default now()
);

create table comentario_diario (
    id integer generated by default as identity primary key,
    diario integer references diario (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  evento
-- -------------------------------------------------------------------

create table evento (                                                                
    id integer generated by default as identity primary key,
    descripcion text,
    fecha timestamp with time zone default now()
);

create table comentario_evento (
    id integer generated by default as identity primary key,
    evento integer references evento (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);
