-- -*- mode: sql; sql-product: postgres -*-

-- id integer generated by default as identity primary key
-- id serial primary key

-- -------------------------------------------------------------------
--  lenguaje de programacion
-- -------------------------------------------------------------------

create table lenguaje_programacion (
    id integer generated by default as identity primary key,
    nombre text
);

create table impresion (
    id integer generated by default as identity primary key,
    nombre text,
    version text,
    lenguaje integer references lenguaje_programacion (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  codigo fuente
-- -------------------------------------------------------------------

create table codigo_fuente (
    id integer generated by default as identity primary key,
    nombre text,
    contenido text,
    lenguaje integer references lenguaje_programacion (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

create table comentario_codigo_fuente (
    id integer generated by default as identity primary key,
    codigo integer references codigo_fuente (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  snippet
-- -------------------------------------------------------------------

create table snippet (
    id integer generated by default as identity primary key,
    descripcion text,
    codigo text,
    lenguaje integer references lenguaje_programacion (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  pregunta
-- -------------------------------------------------------------------

create table autor_pregunta (
    id integer generated by default as identity primary key,
    nombre text,
    fecha timestamp with time zone default now()
);

create table autor_respuesta (
    id integer generated by default as identity primary key,
    nombre text,
    fecha timestamp with time zone default now()
);

create table pregunta (
    id integer generated by default as identity primary key,
    autor integer references autor_pregunta (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table respuesta (
    id integer generated by default as identity primary key,
    pregunta integer references pregunta (id) on delete cascade on update cascade,
    autor integer references autor_respuesta (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table comentario_pregunta (
    id integer generated by default as identity primary key,
    pregunta integer references pregunta (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table comentario_respuesta (
    id integer generated by default as identity primary key,
    respuesta integer references respuesta (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  repositorio
-- -------------------------------------------------------------------

create table repositorio (
    id integer generated by default as identity primary key,
    descripcion text,
    contenido text,
    fecha timestamp with time zone default now()
);

create table comentario_repositorio (
    id integer generated by default as identity primary key,
    repositorio integer references repositorio(id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);
