-- -*- mode: sql; sql-product: postgres -*-

-- id integer generated by default as identity primary key
-- id serial primary key

-- -------------------------------------------------------------------
--  documento
-- -------------------------------------------------------------------

create table formato_documento (
    id integer generated by default as identity primary key,
    nombre text,
    fecha timestamp with time zone default now()
);

create table documento (
    id integer generated by default as identity primary key,
    titulo text,
    contenido text,
    formato integer references formato_documento (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

create table comentario_documento (
    id integer generated by default as identity primary key,
    documento integer references documento (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

-- -------------------------------------------------------------------
--  libro
-- -------------------------------------------------------------------

create table libro (
    id integer generated by default as identity primary key,
    titulo text,
    autor text,
    fecha timestamp with time zone default now()
);

create table parrafo_libro (
    id integer generated by default as identity primary key,
    libro integer references libro (id) on delete cascade on update cascade,
    referencia text,
    contenido text,
    fecha timestamp with time zone default now()
);

create table comentario_parrafo_libro (
    id integer generated by default as identity primary key,
    parrafo integer references parrafo_libro (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);
