-- -*- mode: sql; sql-product: postgres -*-

-- id integer generated by default as identity primary key
-- id serial primary key

-- -------------------------------------------------------------------
--  expresion idiomatica
-- -------------------------------------------------------------------

create table idioma (
    id integer generated by default as identity primary key,
    nombre text
);

create table expresion_idiomatica (
    id integer generated by default as identity primary key,
    oracion text,
    significado text,
    idioma integer references idioma (id) on delete cascade on update cascade,
    fecha timestamp with time zone default now()
);

create table comentario_expresion_idiomatica (
    id integer generated by default as identity primary key,
    expresion integer references expresion_idiomatica (id) on delete cascade on update cascade,
    contenido text,
    fecha timestamp with time zone default now()
);

create table japones (
    id integer generated by default as identity primary key,
    escritura text,
    romaji text,
    traduccion text,
    fecha timestamp with time zone default now()
);
